### ISSUE TITLE
Playground: Cyrillic doesn't work

### ISSUE THREAD

**Issue by safinaskar** [sf-web/sf-web.github.io#11]
http://sourcefoundry.org/hack/ reports that font "hack" supports Cyrillic: "Over 1500 glyphs that include lovingly tuned expanded Latin, modern Greek, and Cyrillic character sets".

But this playground seem not to support it. When I type some Cyrillic to it (for example, "абв"), this Cyrillic letter have width, which is not equal to width of Latin letters

**Comment by chrissimpkins** [comment]
Working on a fix.  I think that @burodepeper identified the problem.  Will let you know when it is ready.  Apologies!

**Comment by chrissimpkins** [comment]
Mind giving it a try again to verify that it works now?  It should be fixed.

**Comment by safinaskar** [comment]
It works, thanks :)

**Comment by chrissimpkins** [comment]
excellent! thanks for the report.  it was a simple oversight.  

cc @burodepeper
