### ISSUE TITLE
Playground: side by side bug

### ISSUE THREAD

**Issue by bwanaaa** [sf-web/sf-web.github.io#13]
in 'compare side by side' the left hand pane only show 18 lines

**Comment by chrissimpkins** [comment]
ty!

@jublo thoughts?

**Comment by jublo** [comment]
Will take a look. @chrissimpkins Can you import me to this repo/orga?

**Comment by chrissimpkins** [comment]
Please PR changes to website JM.

**Comment by chrissimpkins** [comment]
@bwanaaa JM's changes for this issue are merged and live on the site.  See PR #14 for changes.  Please verify that they fix this issue for you.  OK to close this IR if so.

**Comment by chrissimpkins** [comment]
@jublo I reopened to allow OP to comment on revisions.  Seems that no further testing happening on their end.  OK to close again?  You can confirm that this is fixed?

**Comment by jublo** [comment]
Yes, the left editor is resized all the way down once you switch on side-by-side – you can see this at the indent guide – which stopped after line 18 before.
