### ISSUE TITLE
Firefox font menu rendering in Font Playground

### ISSUE THREAD

**Issue by chrissimpkins** [sf-web/sf-web.github.io#18]
@jublo 

I am seeing grey text on grey background for the font name rendering in the side by side view of Font Playground with Firefox 56.0b12 on OS X.

![2017-09-20 10 47 36](https://user-images.githubusercontent.com/4249591/30650814-dcc10dd6-9df1-11e7-9db8-4c6cb829677c.gif)

Can confirm that this is not present on OS X releases of Chrome Version 61.0.3163.91 (Official Build) (64-bit), Brave 0.18.36, and Safari Version 11.0 (12604.1.38.1.7).

Thoughts?

**Comment by jublo** [comment]
Microsoft Edge is not really better.

<img width="551" alt="bildschirmfoto 2017-09-20 um 17 00 29" src="https://user-images.githubusercontent.com/6348321/30651181-4261995c-9e25-11e7-83ad-5c91b44b7ceb.png">
