### ISSUE TITLE
Playground: Add toggle button (idea)

### ISSUE THREAD

**Issue by hoschi** [sf-web/sf-web.github.io#20]
So user can toggle between two fonts directly. This would make it a lot easier to compare current font and "font I wanna try", because you can focus on details and toggle without loosing focus for open the select box.

**Comment by hoschi** [comment]
lol, found the "compare side by side" button

**Comment by chrissimpkins** [comment]
:+1:  may be worth leaving open to make more apparent?

cc @jublo

**Comment by jublo** [comment]
@hoschi Suggestions on a better visual approach?

**Comment by hoschi** [comment]
put it into the main content area would be great :+1:
